package com.example.pokemontypecalculator

import java.sql.Types
import java.util.*

class TypeMatchups(
    val Bug: Map<String, Double>,
    val Dark: Map<String, Double>,
    val Dragon: Map<String, Double>,
    val Electric: Map<String, Double>,
    val Fairy: Map<String, Double>,
    val Fighting: Map<String, Double>,
    val Fire: Map<String, Double>,
    val Flying: Map<String, Double>,
    val Ghost: Map<String, Double>,
    val Grass: Map<String, Double>,
    val Ground: Map<String, Double>,
    val Ice: Map<String, Double>,
    val Normal: Map<String, Double>,
    val Poison: Map<String, Double>,
    val Psychic: Map<String, Double>,
    val Rock: Map<String, Double>,
    val Steel: Map<String, Double>,
    val Water: Map<String, Double>
)

//older iteration
//
//class Interactions(
//    val Bug: BugInteractions,
//    val Dark: DarkInteractions,
//    val Dragon: DragonInteractions,
//    val Electric: ElectricInteractions,
//    val Fairy: FairyInteractions,
//    val Fighting: FightingInteractions,
//    val Fire: FireInteractions,
//    val Flying: FlyingInteractions,
//    val Ghost: GhostInteractions,
//    val Grass: GrassInteractions,
//    val Ground: GroundInteractions,
//    val Ice: IceInteractions,
//    val Normal: NormalInteractions,
//    val Poison: PoisonInteractions,
//    val Psychic: PsychicInteractions,
//    val Rock: RockInteractions,
//    val Steel: SteelInteractions,
//    val Water: WaterInteractions
//)
//class BugInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class DarkInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class DragonInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class ElectricInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class FairyInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class FightingInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class FireInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class FlyingInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class GhostInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class GrassInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class GroundInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class IceInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class NormalInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class PoisonInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class PsychicInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class RockInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class SteelInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)
//class WaterInteractions(
//    val Bug: Double = 1.0,
//    val Dark: Double = 1.0,
//    val Dragon: Double = 1.0,
//    val Electric: Double = 1.0,
//    val Fairy: Double = 1.0,
//    val Fighting: Double = 1.0,
//    val Fire: Double = 1.0,
//    val Flying: Double = 1.0,
//    val Ghost: Double = 1.0,
//    val Grass: Double = 1.0,
//    val Ground: Double = 1.0,
//    val Ice: Double = 1.0,
//    val Normal: Double = 1.0,
//    val Poison: Double = 1.0,
//    val Psychic: Double = 1.0,
//    val Rock: Double = 1.0,
//    val Steel: Double = 1.0,
//    val Water: Double = 1.0
//)